name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Configure NuGet
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/Yuman-net/index.json --name GitHub --username and.nik.dev@gmail.com --password ${{ secrets.PKG_SECRET }} --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore --packages ./nupkgs

    - name: Build project
      run: dotnet build --configuration Release

    - name: Pack Entities
      run: dotnet pack Abstract.Domain/Domain.Entities.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Pack DataAccess
      run: dotnet pack Abstract.DataAccess/DataAccess.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Pack Models
      run: dotnet pack Models.Abstractions/Models.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Pack Services
      run: dotnet pack Services.Abstractions/Services.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Pack WebApi
      run: dotnet pack WebApi.Abstractions/WebApi.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Publish NuGet package
      env:
        PKG_SECRET: ${{ secrets.PKG_SECRET }}
      run: |
        dotnet nuget push ./nupkgs/*.nupkg --source "GitHub" --api-key $PKG_SECRET --skip-duplicate
