name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Create NuGet.config
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <add key="GitHub" value="https://nuget.pkg.github.com/Yuman/index.json" />
          </packageSources>
        </configuration>' > NuGet.config
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Pack Entities
      run: dotnet pack Abstract.Domain/Domain.Entities.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Pack DataAccess
      run: dotnet pack Abstract.DataAccess/DataAccess.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Pack Models
      run: dotnet pack Models.Abstractions/Models.Abstractions.csproj --configuration Release --output ./nupkgs

    - name: Publish NuGet package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget push ./nupkgs/*.nupkg --source "GitHub" --api-key $GITHUB_TOKEN
